application: opencraft-otp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: otp.app
  secure: always

libraries:
- name: pycrypto
  version: "latest"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\..*$
